G2_R_R(logic_less_equal_l){IDX; ASSIGN_R(0<=xr[idx]);}
G2_R_C(logic_less_equal_l){IDX; ASSIGN_R(0<=xr[idx]);}
G2_R_Q(logic_less_equal_l){IDX; ASSIGN_R(0<=xr[idx]);}
G2_R_R(logic_less_equal_r){IDX; ASSIGN_R(xr[idx]<=0);}
G2_R_C(logic_less_equal_r){IDX; ASSIGN_R(xr[idx]<=0);}
G2_R_Q(logic_less_equal_r){IDX; ASSIGN_R(xr[idx]<=0);}
G2_R_RR(logic_less_equal){IDX; ASSIGN_R(xr[idx]<=yr[idx]);}
G2_R_RC(logic_less_equal){IDX; ASSIGN_R(xr[idx]<=yr[idx]);}
G2_R_RQ(logic_less_equal){IDX; ASSIGN_R(xr[idx]<=yr[idx]);}
G2_R_CR(logic_less_equal){IDX; ASSIGN_R(xr[idx]<=yr[idx]);}
G2_R_CC(logic_less_equal){IDX; ASSIGN_R(xr[idx]<=yr[idx]);}
G2_R_CQ(logic_less_equal){IDX; ASSIGN_R(xr[idx]<=yr[idx]);}
G2_R_QR(logic_less_equal){IDX; ASSIGN_R(xr[idx]<=yr[idx]);}
G2_R_QC(logic_less_equal){IDX; ASSIGN_R(xr[idx]<=yr[idx]);}
G2_R_QQ(logic_less_equal){IDX; ASSIGN_R(xr[idx]<=yr[idx]);}
DISC_R_O(logic_less_equal){IDX; disc[idx]=xr[idx]!=xr[idx+offset];}

G2_R_R(logic_greater_l){IDX; ASSIGN_R(0>xr[idx]);}
G2_R_C(logic_greater_l){IDX; ASSIGN_R(0>xr[idx]);}
G2_R_Q(logic_greater_l){IDX; ASSIGN_R(0>xr[idx]);}
G2_R_R(logic_greater_r){IDX; ASSIGN_R(xr[idx]>0);}
G2_R_C(logic_greater_r){IDX; ASSIGN_R(xr[idx]>0);}
G2_R_Q(logic_greater_r){IDX; ASSIGN_R(xr[idx]>0);}
G2_R_RR(logic_greater){IDX; ASSIGN_R(xr[idx]>yr[idx]);}
G2_R_RC(logic_greater){IDX; ASSIGN_R(xr[idx]>yr[idx]);}
G2_R_RQ(logic_greater){IDX; ASSIGN_R(xr[idx]>yr[idx]);}
G2_R_CR(logic_greater){IDX; ASSIGN_R(xr[idx]>yr[idx]);}
G2_R_CC(logic_greater){IDX; ASSIGN_R(xr[idx]>yr[idx]);}
G2_R_CQ(logic_greater){IDX; ASSIGN_R(xr[idx]>yr[idx]);}
G2_R_QR(logic_greater){IDX; ASSIGN_R(xr[idx]>yr[idx]);}
G2_R_QC(logic_greater){IDX; ASSIGN_R(xr[idx]>yr[idx]);}
G2_R_QQ(logic_greater){IDX; ASSIGN_R(xr[idx]>yr[idx]);}
DISC_R_O(logic_greater){IDX; disc[idx]=xr[idx]!=xr[idx+offset];}

G2_R_R(logic_greater_equal_l){IDX; ASSIGN_R(0>=xr[idx]);}
G2_R_C(logic_greater_equal_l){IDX; ASSIGN_R(0>=xr[idx]);}
G2_R_Q(logic_greater_equal_l){IDX; ASSIGN_R(0>=xr[idx]);}
G2_R_R(logic_greater_equal_r){IDX; ASSIGN_R(xr[idx]>=0);}
G2_R_C(logic_greater_equal_r){IDX; ASSIGN_R(xr[idx]>=0);}
G2_R_Q(logic_greater_equal_r){IDX; ASSIGN_R(xr[idx]>=0);}
G2_R_RR(logic_greater_equal){IDX; ASSIGN_R(xr[idx]>=yr[idx]);}
G2_R_RC(logic_greater_equal){IDX; ASSIGN_R(xr[idx]>=yr[idx]);}
G2_R_RQ(logic_greater_equal){IDX; ASSIGN_R(xr[idx]>=yr[idx]);}
G2_R_CR(logic_greater_equal){IDX; ASSIGN_R(xr[idx]>=yr[idx]);}
G2_R_CC(logic_greater_equal){IDX; ASSIGN_R(xr[idx]>=yr[idx]);}
G2_R_CQ(logic_greater_equal){IDX; ASSIGN_R(xr[idx]>=yr[idx]);}
G2_R_QR(logic_greater_equal){IDX; ASSIGN_R(xr[idx]>=yr[idx]);}
G2_R_QC(logic_greater_equal){IDX; ASSIGN_R(xr[idx]>=yr[idx]);}
G2_R_QQ(logic_greater_equal){IDX; ASSIGN_R(xr[idx]>=yr[idx]);}
DISC_R_O(logic_greater_equal){IDX; disc[idx]=xr[idx]!=xr[idx+offset];}